### ISSUE TITLE
Can't get LFM to work

### ISSUE THREAD

**Issue by gizburdt** [emilianotisato/nova-tinymce#10]
Hi,

Awesome package!

I can't get the image upload with LFM to work (I don't see an image upload icon in the TinyMCE toolbars). This is in my Nova Resource:

```
NovaTinyMCE::make('Content')
                ->options([
                    'use_lfm' => true,
                ])
```

The LFM package is installed via composer.

Am I missing something?

**Comment by emilianotisato** [comment]
@gizburdt Yes, you are not adding the 'plugins' and the 'toolbar' keys in the options array. This is needed because otherwise javascript (the TinyMCE script) doe't no kwon witch tools to render in the toolbar.

Did you see the example in the readme for this repo??

**Comment by gizburdt** [comment]
Ah ok!

Which values do I need to set in plugins/toolbar to enable the image upload with lfm?

Thanks! :)

**Comment by emilianotisato** [comment]
Start with this:

```
NovaTinyMCE::make('body')->options([
                'plugins' => [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern'
                ],
                'toolbar' => 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media',
                'use_lfm' => true
                ]),
```

And then remove the plugins and toolbar options you don't need

**Comment by gizburdt** [comment]
Ok thanks! :)

**Comment by michapixel** [comment]
i had to fiddel the lfm_url too and set a route:
```
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
  	\UniSharp\LaravelFilemanager\Lfm::routes();
});
```
