### ISSUE TITLE
Display editor in larger size (vertical)

### ISSUE THREAD

**Issue by akmalelias** [emilianotisato/nova-tinymce#13]
Hi, is it possible to make the editor vertically bigger?
Something similar to the rows() function for Textarea field.

Thanks

**Comment by emilianotisato** [comment]
Hello @akmalelias ,

Sure, you can pass any argument allowed by the tinyMCE sdk. to the options array:
```php
            NovaTinyMCE::make('my-textarea-column')->options(['height' => '980']),
```
