### ISSUE TITLE
Community edition?

### ISSUE THREAD

**Issue by stuartcusackie** [emilianotisato/nova-tinymce#14]
Correct me if I am wrong, but doesn't the API version of TinyMCE limit you to one domain per account? I suppose I could set up an account for every one of my clients but wouldn't it be better if we could use the community edition of TinyMCE? I believe that it's not limited like this.

**Comment by emilianotisato** [comment]
Hello @stuartcusackie 
In did you can have multiple domains with your single free API key. 
In the TinyMCE panel, in the API management secction https://apps.tiny.cloud/my-account/api-key-manager/

You just put a wildcard as the domain: *
