### ISSUE TITLE
Use Expandable trait in order to set alwaysShow()

### ISSUE THREAD

**Issue by RoachMech** [emilianotisato/nova-tinymce#20]
First off: great library! Works very well. Thanks!

I was wondering what would be the best way to implement the option to set the NovaTinyMCE Field to alwaysShow. I think adding the Expandable trait would be the best option. What do you think? Or are there any other ways to set alwaysShow?

**Comment by emilianotisato** [comment]
Hello @RoachMech ,
It is already working with the nova `alwayShow()` method since this field extends Expandable trait.

You just need to call it in your resource like this:
```php
            NovaTinyMCE::make('Body')->alwaysShow(),
```

**Comment by RoachMech** [comment]
Thanks @emilianotisato! For some reason I was on version 0.5.4. I've run `composer require emilianotisato/nova-tinymce` again and the library was updated to 1.1.1. Sorry for the confusion.
