### ISSUE TITLE
FileManager Integration Problem

### ISSUE THREAD

**Issue by Milkhan** [emilianotisato/nova-tinymce#22]
First of all, thank you for this nice Nova package. 
I tried to integrate File Manager but I got an error after I ran 

 **php artisan nova-tinymcs:suport-lfm**

`copy(/Users/Adem/mavi/exam/resources/views/vendor/laravel-filemanager/index.blade.php): failed to open stream: No such file or directory

  at /Users/Mst/mavi/exam/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:250
    246|      * @return bool
    247|      */
    248|     public function copy($path, $target)
    249|     {
  > 250|         return copy($path, $target);
    251|     }
    252|
    253|     /**
    254|      * Create a hard link to the target file or directory.

  Exception trace:

  1   copy("/Users/Adem/mavi/exam/vendor/emilianotisato/nova-tinymce/src/Console/stubs/laravel-filemanager/index.blade.php", "/Users/Adem/mavi/exam/resources/views/vendor/laravel-filemanager/index.blade.php")
      /Users/Adem/mavi/exam/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:250

  2   Illuminate\Filesystem\Filesystem::copy("/Users/Adem/mavi/exam/vendor/emilianotisato/nova-tinymce/src/Console/stubs/laravel-filemanager/index.blade.php", "/Users/Adem/mavi/exam/resources/views/vendor/laravel-filemanager/index.blade.php")
      /Users/Adem/mavi/exam/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261

  Please use the argument -v to see more details.`

And when I try to open the file manager from the TinyMCE I got a 404 error.
What I missed?

Thank you

**Comment by Milkhan** [comment]
I think your script is looking for a vendor/views/laravel-filemanager folder but current File manager doesn't create these folders in the resources.

**Comment by Milkhan** [comment]
Your package is using the 1.9.2 (or an earlier) version of the FileManager. You are referencing old config parameters, the newest 2.0 doesnt have these parameters.  I tried to downgrade but the thing is it doesn't support Laravel 6.0. I hope you update your package for the newest FileManager.

**Comment by Milkhan** [comment]
I could install 1.9.2. For future reference, please use 1.9.2 of the FileManager.

**Comment by aaronahearne** [comment]
For anyone coming across this I found that I could only get the following combination to work:
"emilianotisato/nova-tinymce": "^0.5.4",
"unisharp/laravel-filemanager": "~1.8",
