### ISSUE TITLE
Problem with Laravel 7 "Unable to locate publishable resources"

### ISSUE THREAD

**Issue by socialab-admin** [emilianotisato/nova-tinymce#27]
I followed the basic steps for its installation and I receive the following error, after executing.

`php artisan vendor:publish --provider="Emilianotisato\NovaTinyMCE\FieldServiceProvider" --tag="config"
`

> Unable to locate publishable resources.

**Comment by emilianotisato** [comment]
This package is not ready for Laravel 7. And Nova 3. Will do that soon but
if you what to submit a PR with that implementation that could be a
starting point.
