### ISSUE TITLE
LFM - can browse files/images but select does nothing

### ISSUE THREAD

**Issue by michapixel** [emilianotisato/nova-tinymce#28]
and no js-error shown ...

**Comment by emilianotisato** [comment]
Can you describe a little more you context, Laravel and Nova versions, etc?

**Comment by michapixel** [comment]
Apache 2.4 
PHP 7.2 
Laravel 5.8 
Nova 2.5

I have installed LFM and your package from what i can see is the current latest version.
So LFM 2.
The FM is shown in an inline-popup (iframe) and i can browse the public directories for it, but 
selecting a file with the buttons does get me back to the directory where that file resides. 
Scaling/cropping also is scrambled / not working.

**Comment by emilianotisato** [comment]
Hello @michapixel 

Did you solve the issue? I am wandering if you follow the LFM integration explained in the readme.
Did you run this command? `php artisan nova-tinymcs:suport-lfm`

**Comment by michapixel** [comment]
> php artisan nova-tinymcs:suport-lfm

you probably meant nova-tinymce. What does this do?

**Comment by emilianotisato** [comment]
You are right, I did have a typo in the command name, now is fixed if you download version 1.1.3

This command was introduced 5 months ago to fix some front end assets of LFM package:
```
php artisan nova-tinymce:suport-lfm
```

We tested with latest version of LFM 1.x but should work with v2

**Comment by michapixel** [comment]
what exactly does 
`php artisan nova-tinymce:suport-lfm` 
do?

**Comment by emilianotisato** [comment]
It fix front end files from LFM packages to work with latest tiny mce

**Comment by michapixel** [comment]
Well that fixed sth in the index.blade.php but now throws an error for me. 

htmlspecialchars() expects parameter 1 to be string, object given:
![firefox_2020-04-30_16-59-16](https://user-images.githubusercontent.com/370877/80725895-f9c7b900-8b03-11ea-91d0-2ab71408b5bc.png)
Something in the blade is wrong. You're pushing an object/array in a echo statement like this:
{{ (object) []; }}

**Comment by michapixel** [comment]
![firefox_2020-04-30_17-07-42](https://user-images.githubusercontent.com/370877/80726784-25976e80-8b05-11ea-87c0-9c07dd811775.png)

**Comment by emilianotisato** [comment]
Are you sure you are using Laravel 5.8?? Because if you are using v6 in the
readme we explained you need to pull the laravel/helpers package, again,
this is not because our package fault but because LMF

**Comment by michapixel** [comment]
Pretty sure.
I'm using the system-info-card from Novapackages. It clearly prints 5.8

Emiliano Tisato <notifications@github.com> schrieb am Do., 30. Apr. 2020,
18:31:

**Comment by emilianotisato** [comment]
I can't reproduce your error. Last thing I am gonna suggest is that you clear your laravel caches, config cache, view cache and route cache. Maybe some old assets are persisting

**Comment by michapixel** [comment]
Okay, I'm for the weekend, will try on Monday. 🤷🏼‍♂️

Emiliano Tisato <notifications@github.com> schrieb am Do., 30. Apr. 2020,
19:06:
