### ISSUE TITLE
Config File Missing

### ISSUE THREAD

**Issue by DerekBuntin** [emilianotisato/nova-tinymce#29]
The config file is missing from the package and cannot be published:

`php artisan vendor:publish --provider="Emilianotisato\NovaTinyMCE\FieldServiceProvider" --tag="config"

Unable to locate publishable resources.
`

I just noticed https://github.com/emilianotisato/nova-tinymce/issues/27

It's L7 I use and I've tried reinstalling but to no avail, has this not yet been resolved?

**Comment by michapixel** [comment]
Had the same issues last Week, i just copied it myself.

**Comment by emilianotisato** [comment]
I see it is not a package issue but in general something with laravel and packages:
https://github.com/laravel/nova-issues/issues/2489
