### ISSUE TITLE
work with spatie/nova-translatable, nova

### ISSUE THREAD

**Issue by Enmaboya** [emilianotisato/nova-tinymce#3]
why the field does not work with spatie/nova-translatable ?
just empty field

    Translatable::make([
            NovaTinyMCE::make('translatable_value'),
    ]),
but if i write

    Translatable::make([
            NovaTinyMCE::make('translatable_value_fr'),
    ]),
The field will appear, but I will not be able to make changes, because I do not have such a field

**Comment by Enmaboya** [comment]
problem in
  :id="field.name"

**Comment by emilianotisato** [comment]
@Enmaboya sorry about the delay.

Could you fix de issue?
