### ISSUE TITLE
Editing source code does not get saved

### ISSUE THREAD

**Issue by daanadriaan** [emilianotisato/nova-tinymce#31]
When I edit the <> source code in the editor, the wysiwyg editor gets updated. Though, when I click Update, the old code gets saved. However, if I edit the source code and continue editing in the wysiwyg editor it works. Since, not all our editors will remember this workaround, I would like to see this issue resolved.

**Comment by emilianotisato** [comment]
I can't reproduce it. Do you have some addblocker or other context config (browser? version?) the help in debugging ?

**Comment by daanadriaan** [comment]
Solved!

It was a custom external_plugin that caused the trouble. I can't figure out what the problem was, but I managed to solve the problem in the plugin and things seem to be working again.

Thanks anyway <3 Love the package
