### ISSUE TITLE
event options for tinymce 

### ISSUE THREAD

**Issue by michapixel** [emilianotisato/nova-tinymce#32]
are there any? these should have been declared as (anonymous) functions, but how can this be done fropm the confih (php)?
If not, any ideas how i can intercept the content before it get's into the editor?

**Comment by emilianotisato** [comment]
@michapixel Sorry for not doing a proper follow up on this.

If you mean javascript events, you do have all the events the library emits. Please read the TinyMCE docs to work with events.

If you referred to something else, can you specify?

About the content interception, you can do it the nova way, with methods like `->displayUsing()`
