### ISSUE TITLE
Why use LFM?

### ISSUE THREAD

**Issue by paulocastellano** [emilianotisato/nova-tinymce#33]
Tinymce have upload imagens by default, you can just pass url for upload:

```images_upload_url```

reference:
[https://www.tiny.cloud/docs/configure/file-image-upload](https://www.tiny.cloud/docs/configure/file-image-upload/)

This makes the project cleaner

**Comment by DerekBuntin** [comment]
> Tinymce have upload imagens by default, you can just pass url for upload:
> 
> `images_upload_url`
> 
> reference:
> [https://www.tiny.cloud/docs/configure/file-image-upload](https://www.tiny.cloud/docs/configure/file-image-upload/)
> 
> This makes the project cleaner

I totally agree and it could be integrated with one fo the other file managers so that it can simply select from the media library.

Paul have you managed to get this working using the images_upload_url option?

**Comment by emilianotisato** [comment]
@paulocastellano @DerekBuntin 
Sure, tinymce has the image capability. But its get's store as base64 encoded image in the payload. 

The LFM integration is intended to be use in the cases where you want to store that images in the server.
You can opt in or out of this feature, that is why is configurable.
