### ISSUE TITLE
Show content by default on detail view

### ISSUE THREAD

**Issue by iMuMz** [emilianotisato/nova-tinymce#35]
Hi,

Is it possible to show the content by default on the detail view of a resource?

**Comment by iMuMz** [comment]
I tried the default Nova feature `->alwaysShow()` but the method does not exist with the nova-tinymce package.

![Screenshot 2020-06-07 at 07 58 03](https://user-images.githubusercontent.com/22936672/83961587-d9beae80-a894-11ea-8dcd-a67aeeabd969.png)

As a work  around, I use the Nova text field and return the content as html :

`Text::make('Content', function () {})->onlyOnDetail()->asHtml()
`

**Comment by emilianotisato** [comment]
Sorry, do you still have this issue? Can you tell witch nova version you are using?

**Comment by emilianotisato** [comment]
@iMuMz Does this problem persist on your project? Did you manage to solve it?

**Comment by iMuMz** [comment]
@emilianotisato Yes I still have this issue but I will use the workaround until I update : 

`Text::make('Content', function () {
   return $this->content;
})->onlyOnDetail()->asHtml()`

Laravel : 6.16.0
Nova: 2.10.1

![Screenshot 2020-09-16 at 14 54 02](https://user-images.githubusercontent.com/22936672/93340190-cd030c80-f82c-11ea-8dc7-85b7d6eed28e.png)
