### ISSUE TITLE
localization?

### ISSUE THREAD

**Issue by vmihaly2020** [emilianotisato/nova-tinymce#38]
I know is it an option "language"=> 'sv_SE' in config file
But how can I install sv_SE.js language file?

**Comment by emilianotisato** [comment]
Hello @vmihaly2020,
As we mention in the documentation, this integration allow you to fully use the tinymce javascript sdk, so for any use case you need to refere to the tinymce documentation.

A single minute researching tell's me that you need to download the language file and have the sdk know of the location in the options like this 
```javascript
 language_url : '/languages/fi.js'  // site absolute URL
```

https://www.tiny.cloud/docs/configure/localization/
