### ISSUE TITLE
Not possible to add Tiny MCE key

### ISSUE THREAD

**Issue by aaronahearne** [emilianotisato/nova-tinymce#43]
When deployed to a live production site, a warning is shown in place of the editor that the Tiny MCE key is missing, but there is no way to enter a key for this package to use.

**Comment by alberto-bottarini** [comment]
https://github.com/emilianotisato/nova-tinymce/issues/37

You are right, but @emilianotisato do not agree with us

**Comment by alberto-bottarini** [comment]
@emilianotisato https://www.tiny.cloud/docs/integrations/vue/#api-key

**Comment by emilianotisato** [comment]
Tiny MCE is changing the way to work. On the pass we have the ability to set the key, the we remove it coz it was no longer mandatory to use the script.

Now seems to be back?
Can any one send a PR setting again the option to initialize the script with a valid account key?

**Comment by yuriy-martini** [comment]
No need for API key because of https://www.tiny.cloud/docs/general-configuration-guide/advanced-install/#self-hostedinstall
