### ISSUE TITLE
autoresize not working

### ISSUE THREAD

**Issue by JonathanDoelan** [emilianotisato/nova-tinymce#48]
Thx for your work!

[Autoresize](https://www.tiny.cloud/docs/plugins/opensource/autoresize/) is not working.
This has no effect:

(`config/nova-tinymce.php`)
```
'plugins' => [
	'autoresize',
],

'autoresize_bottom_margin'		=> 0,
'autoresize_min_height'			=> 120,
'autoresize_max_height'			=> 1000,
'autoresize_overflow_padding'	=> 0,
```

simple `'resize' => true` is also not working

**Comment by gserrg** [comment]
See #49

**Comment by JonathanDoelan** [comment]
@gserrg Thx!
