### ISSUE TITLE
Not all tinymce plugins are supported.

### ISSUE THREAD

**Issue by gserrg** [emilianotisato/nova-tinymce#49]
Hi @emilianotisato, please note, this solves many issues.

Open source plugins at tinymce: https://www.tiny.cloud/docs/plugins/opensource/

Nova-tinymce only supports https://github.com/emilianotisato/nova-tinymce/blob/master/resources/js/tinymce.js#L8-L37

Thus, there is no support: `Autoresize`, `Autosave`, `Noneditable` and others (11 in total). If this is done on purpose, then the readme.md must indicate a list of not supported.

**Comment by gserrg** [comment]
Temporary solution: copy the folder with the required plugin from https://github.com/tinymce/tinymce-dist/tree/master/plugins to  /public/nova-api/scripts/plugins of the project

**Comment by emilianotisato** [comment]
Hello @gserrg ,

This package implements a wrapper around  tinymce library so adding plugs should work as indicated in official tinymce documentation. It is enough for you to make the plugin scripts available at window level.

If you came up with a better solution please feel free to send a PR.

Thanks in advence!
Emiliano

**Comment by gserrg** [comment]
So I indicated in the description that the list of supported plugins is clearly limited in nova-tinymce, all the rest must be loaded manually. All this is not obvious without examining the code. Therefore it is worth at least to indicate the list of those supported in readme.md. Sorry my english is bad for editing the documentation via PR.
