### ISSUE TITLE
On Laravel Vapor, CSS files are not found

### ISSUE THREAD

**Issue by conantp** [emilianotisato/nova-tinymce#59]
When deploying via Laravel Vapor, the CSS / skin files don't reference the assets URL, and return a 404 (breaking the editor).  

I believe it would be resolved if you run those assets through the "asset" function.

**Comment by bessa3301** [comment]
have you checked the issue #53 ? As it does not exactly solves the problem, it maybe can help you out.

**Comment by egantz** [comment]
@conantp Serving the files via external CDN does the trick! 

Set your `config/nova-tinymce.php` to be:
```
'content_css' => 'https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.4.2/skins/ui/oxide/content.min.css',
'skin_url' => 'https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.4.2/skins/ui/oxide',
'content_css_dark' => 'https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.4.2/skins/ui/oxide-dark/content.min.css',
'skin_url_dark' => 'https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.4.2/skins/ui/oxide-dark',
```

And you're good!

**Comment by conantp** [comment]
@egantz - thanks for the heads up! I'm not sure where I found the solution months ago but yes, I can confirm using the CDN did fix the issue for me as well!
